# Generated by Django 5.1.4 on 2025-03-14 22:56

import django.db.models.deletion
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen1', models.TextField()),
                ('imagen2', models.TextField(blank=True, null=True)),
                ('imagen3', models.TextField(blank=True, null=True)),
                ('imagen4', models.TextField(blank=True, null=True)),
                ('imagen5', models.TextField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Computadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nmRol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Compatibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componente_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base', to='builder.componente')),
                ('componente_compatible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatible', to='builder.componente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleComputadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.componente')),
                ('computadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.computadora')),
            ],
        ),
        migrations.AddField(
            model_name='componente',
            name='tipo_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='builder.tipocomponente'),
        ),
        migrations.CreateModel(

            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=200, unique=True)),
                ('contraseña', models.CharField(max_length=200)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='builder.rol')),
            ],
        ),
        migrations.AddField(
            model_name='computadora',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.usuario'),
        ),

        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.componente')),
                ('computadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.computadora')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.venta')),
            ],
        ),
    ]
