# Generated by Django 5.1.4 on 2025-04-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_remove_usuario_contraseña_usuario_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='descripcion',
            field=models.CharField(default='Sin descripcion', max_length=200),
        ),
        migrations.AlterField(
            model_name='detallecomputadora',
            name='computadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='builder.computadora'),
        ),
    ]
