# Generated by Django 5.1.4 on 2025-04-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_usuario_token_expiration'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='certificacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='consumo_watts',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='potencia_watts',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='compatibilidad',
            unique_together={('componente_base', 'componente_compatible')},
        ),
    ]
