# Generated by Django 5.1.4 on 2025-04-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_componente_certificacion_componente_consumo_watts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.TextField()),
            ],
        ),
    ]
